name: Build Docker image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Build dockerfile and push image to Docker Hub and Github Registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            f1nnm/contact-backend:${{ github.run_number }}
            f1nnm/contact-backend:latest
            ghcr.io/f1nnm/contact-backend:${{ github.run_number }}
            ghcr.io/f1nnm/contact-backend:latest
      -
        name: Print tag
        run: echo "Tagged images with latest and $GITHUB_RUN_NUMBER"